stages:
    - build
    - deploy

.build:
    stage: build
    timeout: 4h
    artifacts:
        paths: [dist]
    script:
        - mkdir -p "$HOME/.config" && echo "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" > "$HOME/.config/wipal-artifactory-key"
        - ./build.sh
    cache:
        paths: [.ergo_work/**]

linux:
    tags: [docker]
    extends: .build
    image: 
        name: ubuntu:20.04
        entrypoint:
            - bash
            - -c
            - >
                apt-get update &&
                apt-get install sudo &&
                useradd -m default &&
                echo "default ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/default &&
                exec su default -c bash
    before_script:
        - sudo docker/setup.sh
        - export XDG_CACHE_HOME=$CI_PROJECT_DIR/.config

apple:
    tags: [macos]
    extends: .build
    cache: 
