stages:
    - build
    - deploy

.build:
    stage: build
    artifacts:
        paths: [dist]

linux:
    tags: [docker]
    extends: .build
    script:
        - apt-get update && apt-get install -y curl
        - ./build.sh

apple:
    tags: [macos]
    extends: .build
    script:
        - ./build.sh
