stages:
    - build
    - deploy

.build:
    stage: build
    timeout: 4h
    artifacts:
        paths: ["dist-$CI_JOB_NAME"]
    script:
        - mkdir -p "$HOME/.config" && echo "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" > "$HOME/.config/wipal-artifactory-key"
        - ./build.sh
        - mv dist "dist-$CI_JOB_NAME"
    cache:
        paths: [.ergo_work/**]

linux:
    tags: [docker]
    extends: .build
    image: 
        name: ubuntu:20.04
        entrypoint:
            - bash
            - -c
            - >
                apt-get update &&
                apt-get install sudo &&
                useradd -m default &&
                echo "default ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/default &&
                exec su default -c bash
    before_script:
        - sudo docker/setup.sh
        - export XDG_CACHE_HOME=$CI_PROJECT_DIR/.config

apple:
    tags: [macos]
    extends: .build
    cache:
        paths: [.ergo_work/**]

deploy:
    stage: deploy
    rules:
        - if: "$CI_COMMIT_TAG"
    dependencies: [apple, linux]
    image: ubuntu:20.04
    script:
        - apt-get update && apt-get install curl
        - curl -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/linux-64/" -T "dist-linux/*.tar.bz2"
        - curl -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/linux-64-cxx03/" -T "dist-linux/*.tar.bz2"
        - curl -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/osx-64/" -T "dist-apple/*.tar.bz2"
