stages:
    - build
    - deploy

.build:
    stage: build
    timeout: 6h
    artifacts:
        paths: ["dist-$CI_JOB_NAME"]
    script:
        - ./build.sh
        - mv dist "dist-$CI_JOB_NAME"
        - ls
    cache:
        when: always
        paths: [.ergo_work/]

.linux:
    extends: .build
    image: 
        name: ubuntu:22.04
        entrypoint:
            - bash
            - -c
            - >
                apt-get update &&
                apt-get install -y sudo &&
                useradd -m default &&
                echo "default ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/default &&
                exec su default -c bash
    before_script:
        - sudo docker/setup.sh
        - sudo cp docker/*.crt /usr/local/share/ca-certificates
        - sudo update-ca-certificates
        - export XDG_CACHE_HOME=$CI_PROJECT_DIR/.config
        - mkdir -p "$HOME/.config/ergo/http"
        - echo "lgs-gitlab.redacted.invalid = { bearer-auth = $GITLAB_READ_API_TOKEN }, ws-apps.redacted.invalid/artifactory = { basic-auth = \"$ARTIFACTORY_USER:$ARTIFACTORY_KEY\" }" > "$HOME/.config/ergo/http/defaults.ergo"

.apple:
    extends: .build
    before_script:
        - mkdir -p "$HOME/Library/Preferences/ergo/http"
        - echo "lgs-gitlab.redacted.invalid = { bearer-auth = $GITLAB_READ_API_TOKEN }, ws-apps.redacted.invalid/artifactory = { basic-auth = \"$ARTIFACTORY_USER:$ARTIFACTORY_KEY\" }" > "$HOME/Library/Preferences/ergo/http/defaults.ergo"

linux:
    tags: [docker]
    extends: .linux

apple:
    tags: [macos]
    extends: .apple

apple-arm64:
    tags: [macos-arm64]
    extends: .apple

deploy:
    stage: deploy
    rules:
        - if: "$CI_COMMIT_TAG"
    dependencies: [apple, apple-arm64, linux]
    image: ubuntu:22.04
    script:
        - apt-get update && apt-get install -y curl
        - curl --fail-with-body -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/linux-64/" -T dist-linux/*.tar.bz2
        - curl --fail-with-body -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/linux-64-cxx03/" -T dist-linux/*.tar.bz2
        - curl --fail-with-body -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/osx-64/" -T dist-apple/*.tar.bz2
        - curl --fail-with-body -u "$ARTIFACTORY_USER:$ARTIFACTORY_KEY" -X PUT "https://ws-apps.redacted.invalid/artifactory/wipal-staging-conda/osx-arm64/" -T dist-apple-arm64/*.tar.bz2
