stages:
    - build
    - deploy

.build:
    stage: build
    artifacts:
        paths: [dist]

linux:
    tags: [docker]
    extends: .build
    image: docker:dind
    script:
        - apk add curl
        - ./build.sh

apple:
    tags: [macos]
    extends: .build
    script:
        - ./build.sh
