stages:
    - build
    - deploy

.build:
    stage: build
    artifacts:
        paths: [dist]
    script:
        - ./build.sh

linux:
    image: curlimages/curl
    tags: [docker]
    extends: .build

apple:
    tags: [macos]
    extends: .build
