name: Test bazel rules

on:
  push:
  workflow_call:
    inputs:
      use-built-toolchain:
        type: boolean
      ref:
        type: string

jobs:

  test-linux-targets:
    strategy:
      matrix:
        host:
          - name: x86_64-unknown-linux-gnu
            runs-on: ubuntu-24.04
          - name: aarch64-unknown-linux-gnu
            runs-on: ubuntu-24.04-arm
          - name: x86_64-apple-macos
            runs-on: macos-13
          - name: arm64-apple-macos
            runs-on: macos-14
          - name: x86_64-pc-windows-msvc
            runs-on: windows-2025
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf

    name: test linux targets
    uses: ./.github/workflows/bazel_impl.yml
    with:
      use-built-toolchain: ${{ inputs.use-built-toolchain || false }}
      ref: ${{ inputs.ref }}
      runs-on: ${{ matrix.host.runs-on }}
      host: ${{ matrix.host.name }}
      target: ${{ matrix.target }}

  test-macos-targets:
    strategy:
      matrix:
        host:
          - name: x86_64-apple-macos
            runs-on: macos-13
          - name: arm64-apple-macos
            runs-on: macos-14
        target:
          - x86_64-apple-macos
          - arm64-apple-macos

    name: test macOS targets
    uses: ./.github/workflows/bazel_impl.yml
    with:
      use-built-toolchain: ${{ inputs.use-built-toolchain || false }}
      ref: ${{ inputs.ref }}
      runs-on: ${{ matrix.host.runs-on }}
      host: ${{ matrix.host.name }}
      target: ${{ matrix.target }}

  test-windows-targets:
    strategy:
      matrix:
        host:
          - name: x86_64-pc-windows-msvc
            runs-on: windows-2025
        target:
          - x86_64-pc-windows-msvc

    name: test Windows targets
    uses: ./.github/workflows/bazel_impl.yml
    if: false # disable this for now, pending upstream rules_cc changes
    with:
      use-built-toolchain: ${{ inputs.use-built-toolchain || false }}
      ref: ${{ inputs.ref }}
      runs-on: ${{ matrix.host.runs-on }}
      host: ${{ matrix.host.name }}
      target: ${{ matrix.target }}
