name: Build toolchain

on:
  push:
  workflow_dispatch:
    inputs:
      build_number:
        description: Extra build number (for multiple releases in one day)
        required: true
        default: 0

jobs:

  build-gcc:
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - name: armv7-unknown-linux-gnueabihf
            os: ubuntu-24.04
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
    name: gcc ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    env:
      gccdir: toolchain/gcc/targets/${{ matrix.target.name }}/toolchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: toolchain/gcc/targets/${{ matrix.target.name }}/toolchain/**/*
          key: gcc-${{ matrix.target.os }}-${{ matrix.target.name }}-${{ hashFiles('toolchain/gcc/Makefile', 'toolchain/gcc/targets/*/.config') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y diffutils gawk libarchive-tools libtool-bin help2man ncurses-dev zlib1g-dev python3-dev

          # https://lists.gnu.org/archive/html/bug-texinfo/2024-05/msg00000.html
          sudo apt-get remove texinfo
          mkdir ~/texinfo && curl -L https://ftp.gnu.org/gnu/texinfo/texinfo-7.2.tar.gz | tar --strip-components=1 -zx -C ~/texinfo
          cd ~/texinfo && ./configure && make && sudo make install
      - name: Build gcc
        if: steps.cache.outputs.cache-hit != 'true'
        run: make -C toolchain/gcc targets/${{ matrix.target.name }}/toolchain
      - name: Create artifact archive
        run: tar -cf gcc-${{ matrix.target.name }}.tar $gccdir # maintain case-sensitivity
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ${{ matrix.target.name }} log
          path: toolchain/gcc/targets/${{ matrix.target.name }}/build.log
          if-no-files-found: error
      - name: Upload built gcc
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ matrix.target.name }}
          path: gcc-${{ matrix.target.name }}.tar
          if-no-files-found: error

  build-sysroot:
    needs: build-gcc
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - name: armv7-unknown-linux-gnueabihf
            os: ubuntu-24.04
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
    name: sysroot ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: calebzulawski/setup-bazel@d635e2dbb112cc37d31384804fe1f189d6751035
        with:
          module-root: toolchain
          bazelisk-cache: true
          disk-cache: ${{ github.job }}-${{ matrix.target.name }}
          max-disk-cache-size: 1
          repository-cache: true
      - name: Download built gcc
        uses: actions/download-artifact@v4
        with:
          name: gcc-${{ matrix.target.name }}
      - name: Build sysroot
        run: |
          tar -xf gcc-${{ matrix.target.name }}.tar
          cd toolchain && bazel build //linux:sysroot-package-${{ matrix.target.name }}
      - name: Upload built sysroot
        uses: actions/upload-artifact@v4
        with:
          name: sysroot-${{ matrix.target.name }}
          path: toolchain/bazel-bin/linux/sysroot-*.tar.xz
          if-no-files-found: error

  build-llvm:
    needs: build-gcc
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            type: linux
          - name: x86_64-apple-macos
            os: macos-13
            type: macos
          - name: arm64-apple-macos
            os: macos-14
            type: macos
    name: llvm ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: calebzulawski/setup-bazel@d635e2dbb112cc37d31384804fe1f189d6751035
        with:
          module-root: toolchain
          bazelisk-cache: true
          disk-cache: ${{ github.job }}-${{ matrix.target.name }}
          max-disk-cache-size: 1
          repository-cache: true
      - name: Download built gcc
        if: ${{ contains(matrix.target.name, 'linux') }}
        uses: actions/download-artifact@v4
        with:
          pattern: gcc-*
      - name: Build llvm
        run: |
          find . -name "gcc-*.tar" -exec tar -xf {} \;
          cd toolchain && bazel build //${{ matrix.target.type }}:llvm-package
      - name: Upload built llvm
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.target.name }}
          path: toolchain/bazel-bin/${{ matrix.target.type }}/llvm-*.tar.xz
          if-no-files-found: error

  test-bazel-rules:
    needs: [build-llvm, build-sysroot]
    uses: ./.github/workflows/bazel.yml
    with:
      use-built-toolchain: true

  release:
    needs: test-bazel-rules
    name: Release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '{llvm,sysroot}-*'
          path: artifacts/
          merge-multiple: True
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          VERSION=toolchain-$(date +%Y.%m.%d)
          if [ "${{ inputs.build_number }}" != "0" ]; then VERSION="$VERSION-${{ inputs.build_number }}"; fi
          git tag -a $VERSION -m "Release $VERSION"
          git push --tags
          gh release create $VERSION artifacts/*
        env:
          GH_TOKEN: ${{ github.token }}
