name: Build Toolchain

on:
  push:
  workflow_dispatch:
    inputs:
      build_number:
        description: Extra build number (for multiple releases in one day)
        required: true
        default: 0

jobs:

  build-gcc:
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - name: armv7-unknown-linux-gnueabihf
            os: ubuntu-24.04
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
    name: gcc ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    env:
      gccdir: toolchain/gcc/targets/${{ matrix.target.name }}/toolchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: toolchain/gcc/targets/${{ matrix.target.name }}/toolchain/**/*
          key: gcc-${{ matrix.target.os }}-${{ matrix.target.name }}-${{ hashFiles('toolchain/gcc/Makefile', 'gcc/targets/*/.config') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y diffutils gawk libarchive-tools libtool-bin help2man ncurses-dev zlib1g-dev python3-dev

          # https://lists.gnu.org/archive/html/bug-texinfo/2024-05/msg00000.html
          sudo apt-get remove texinfo
          mkdir ~/texinfo && curl -L https://ftp.gnu.org/gnu/texinfo/texinfo-7.2.tar.gz | tar --strip-components=1 -zx -C ~/texinfo
          cd ~/texinfo && ./configure && make && sudo make install
      - name: Build gcc
        if: steps.cache.outputs.cache-hit != 'true'
        run: make -C toolchain/gcc targets/${{ matrix.target.name }}/toolchain
      - name: Create artifact archive
        run: tar -cf gcc-${{ matrix.target.name }}.tar $gccdir # maintain case-sensitivity
      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ${{ matrix.target.name }} log
          path: toolchain/gcc/targets/${{ matrix.target.name }}/build.log
          if-no-files-found: error
      - name: Upload built gcc
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ matrix.target.name }}
          path: gcc-${{ matrix.target.name }}.tar
          if-no-files-found: error

  build-sysroot:
    needs: build-gcc
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - name: armv7-unknown-linux-gnueabihf
            os: ubuntu-24.04
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
    name: sysroot ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          module-root: toolchain
          bazelisk-cache: true
          disk-cache: ${{ github.job }}-${{ matrix.target.name }}
          repository-cache: true
      - name: Download built gcc
        uses: actions/download-artifact@v4
        with:
          name: gcc-${{ matrix.target.name }}
      - name: Build sysroot
        run: |
          tar -xf gcc-${{ matrix.target.name }}.tar
          cd toolchain && bazel build //linux:sysroot-package-${{ matrix.target.name }}
      - name: Upload built sysroot
        uses: actions/upload-artifact@v4
        with:
          name: sysroot-${{ matrix.target.name }}
          path: toolchain/bazel-bin/linux/sysroot-*.tar.xz
          if-no-files-found: error

  build-llvm:
    needs: build-gcc
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            type: linux
          - name: x86_64-apple-macos
            os: macos-13
            type: macos
          - name: arm64-apple-macos
            os: macos-14
            type: macos
    name: llvm ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          module-root: toolchain
          bazelisk-cache: true
          disk-cache: ${{ github.job }}-${{ matrix.target.name }}
          repository-cache: true
      - name: Download built gcc
        if: ${{ contains(matrix.target.name, 'linux') }}
        uses: actions/download-artifact@v4
        with:
          pattern: gcc-*
      - name: Build llvm
        run: |
          find . -name "gcc-*.tar" -exec tar -xf {} \;
          cd toolchain && bazel build //${{ matrix.target.type }}:llvm-package
      - name: Upload built llvm
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.target.name }}
          path: toolchain/bazel-bin/${{ matrix.target.type }}/llvm-*.tar.xz
          if-no-files-found: error

  test-linux-targets:
    needs: [build-llvm, build-sysroot]
    strategy:
      matrix:
        host:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - name: x86_64-apple-macos
            os: macos-13
          - name: arm64-apple-macos
            os: macos-14
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    name: test ${{ matrix.target }} target on ${{ matrix.host.name }} host
    runs-on: ${{ matrix.host.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          module-root: bazel/test
          bazelisk-cache: true
          disk-cache: false
          repository-cache: false
      - name: Download LLVM
        uses: actions/download-artifact@v4
        with:
          name: llvm-${{ matrix.host.name }}
      - name: Download sysroot
        uses: actions/download-artifact@v4
        with:
          name: sysroot-${{ matrix.target }}
      - name: Build Test
        run: |
          cd bazel/test && bazel build \
              --platforms=@portable_cc_toolchain//platform:${{ matrix.target }} \
              --repo_env=PORTABLE_CC_TOOLCHAIN_LLVM=`pwd`/../../llvm-${{ matrix.host.name }}.tar.xz \
              --repo_env=PORTABLE_CC_TOOLCHAIN_SYSROOT=`pwd`/../../sysroot-${{ matrix.target }}.tar.xz \
              c_binary cpp_binary
      - name: Run Test
        if: ${{ matrix.host.name == matrix.target}}
        run: |
          cd bazel/test
          bazel-bin/c_binary
          bazel-bin/cpp_binary

  test-macos-targets:
    needs: [build-llvm]
    strategy:
      matrix:
        host:
          - name: x86_64-apple-macos
            os: macos-13
          - name: arm64-apple-macos
            os: macos-14
        target:
          - x86_64-apple-macos
          - arm64-apple-macos
    name: test ${{ matrix.target }} target on ${{ matrix.host.name }} host
    runs-on: ${{ matrix.host.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          module-root: bazel/test
          bazelisk-cache: true
          disk-cache: false
          repository-cache: false
      - name: Download LLVM
        uses: actions/download-artifact@v4
        with:
          name: llvm-${{ matrix.host.name }}
      - name: Build Test
        run: |
          cd bazel/test && bazel build \
              --platforms=@portable_cc_toolchain//platform:${{ matrix.target }} \
              --repo_env=PORTABLE_CC_TOOLCHAIN_LLVM=`pwd`/../../llvm-${{ matrix.host.name }}.tar.xz \
              c_binary cpp_binary
      - name: Run Test
        if: ${{ matrix.host.name == matrix.target}}
        run: |
          cd bazel/test
          bazel-bin/c_binary
          bazel-bin/cpp_binary

  release:
    needs: [test-linux-targets, test-macos-targets]
    name: Release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          VERSION=toolchain-$(date +%Y.%m.%d)
          if [ "${{ inputs.build_number }}" != "0" ]; then VERSION="$VERSION-${{ inputs.build_number }}"; fi
          git tag -a $VERSION -m "Release $VERSION"
          git push --tags
          gh release create $VERSION artifacts/*/*
        env:
          GH_TOKEN: ${{ github.token }}
