name: Test bazel rules

on:
  workflow_call:
    inputs:
      use-built-toolchain:
        type: boolean
      ref:
        type: string
      runs-on:
        type: string
        required: true
      host:
        type: string
        required: true
      target:
        type: string
        required: true

jobs:

  test-cmake-rules:
    name: test ${{ inputs.target }} target on ${{ inputs.host }} host
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Download built toolchain
        uses: actions/download-artifact@v4
        if: ${{ inputs.use-built-toolchain }}
        with:
          pattern: '{llvm-${{ inputs.host }},sysroot-${{ inputs.target }},compiler-rt-linux}'
          merge-multiple: True
      - name: Configure built toolchain
        if: ${{ inputs.use-built-toolchain }}
        shell: bash
        run: |
          echo "PORTABLE_CC_TOOLCHAIN_LLVM=`pwd`/llvm-${{ inputs.host }}.tar.xz" >> $GITHUB_ENV
          echo "PORTABLE_CC_TOOLCHAIN_SYSROOT=`pwd`/sysroot-${{ inputs.target }}.tar.xz" >> $GITHUB_ENV

      - name: Build and Test (Debug)
        working-directory: cmake/test
        shell: bash
        run: ./test.sh ${{ inputs.target }} Debug

      - name: Build and Test (RelWithDebInfo)
        working-directory: cmake/test
        shell: bash
        run: ./test.sh ${{ inputs.target }} RelWithDebInfo

      - name: Build and Test (MinSizeRel)
        working-directory: cmake/test
        shell: bash
        run: ./test.sh ${{ inputs.target }} MinSizeRel

      - name: Build and Test (Release)
        working-directory: cmake/test
        shell: bash
        run: ./test.sh ${{ inputs.target }} Release
