name: Release

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: Extra build number (for multiple releases in one day)
        required: true
        default: 0

permissions:
  contents: write
  attestations: write
  id-token: write

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: tag
        run: |
          VERSION=v$(date +%Y.%m.%d)
          if [ "${{ inputs.build_number }}" != "0" ]; then VERSION="$VERSION-${{ inputs.build_number }}"; fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a $VERSION -m "Release $VERSION"
          git push --tags

  test-bazel:
    needs: [tag]
    uses: ./.github/workflows/bazel.yml
    with:
      ref: ${{ needs.tag.outputs.version }}

  test-cmake:
    needs: [tag]
    uses: ./.github/workflows/cmake.yml
    with:
      ref: ${{ needs.tag.outputs.version }}

  generate-version-info:
    needs: [tag]
    uses: ./.github/workflows/version-info.yml
    with:
      ref: ${{ needs.tag.outputs.version }}

  release:
    needs: [tag, test-bazel, test-cmake, generate-version-info]
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.1.0
    with:
      bazel_test_command: true || # we already tested the tag
      prerelease: false
      release_files: "*_portable_cc_toolchain-*.tar.gz"
      tag_name: ${{ needs.tag.outputs.version }}
